server:
  port: 8000

spring:
  application:
    name: service-order
  profiles:
    active: dev
    include: feign
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        import-check:
          enabled: false
        namespace: ${spring.profiles.active:public}
    sentinel:
      transport:
        dashboard: localhost:8080
      eager: true # 关闭默认的懒加载
      web-context-unify: false

logging:
  level:
    com.bryan.order.client: debug

---
spring:
  config:
    activate:
      on-profile: dev
    import:
      - nacos:common.yaml?group=order

---
spring:
  config:
    activate:
      on-profile: test
    import:
      - nacos:common.yaml?group=order

---
spring:
  config:
    activate:
      on-profile: prod
    import:
      - nacos:common.yaml?group=order