server:
  port: 80

spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"

      default-filters:
#        - PrefixPath=/api
#        - AddResponseHeader=X-Response-Default-Red, Default-Blue
      routes:
        - id: order
          uri: lb://service-order
          predicates:
            - Path=/api/order/**
          order: 0
          filters:
            - RewritePath=/api/order/?(?<segment>.*),/$\{segment}
        - id: product
          uri: lb://service-product
          predicates:
            - name: Path
              args:
                patterns: /api/product/**
                matchTrailingSlash: true
          order: 1
          filters:
            - RewritePath=/api/product/?(?<segment>.*),/$\{segment}
        - id: bing
          uri: https://cn.bing.com/
          predicates:
            - name: Path
              args:
                patterns: /search
            - name: Query
              args:
                param: q
                regexp: s
            - Custom=user,bryantaolong